matrix:
- name: SpellCheck
  sources:
    - ./**/*.html
  aspell:
    lang: en
    d: en_US
  pipeline:
    - pyspelling.filters.html:
        comments: false
        attributes:
          - title
          - alt
        ignores:
          - code
          - pre