trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Checkout the GitHub repository using the service connection
  - checkout: self
    persistCredentials: true
  - script: echo "Building the project..."
    displayName: 'Build Project'
