# Simple workflow for PRs in GitHub
name: GitHub Actions PR Workflow

on:
  # Runs on pull requests to main branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Add additional jobs here!!

  # End additional job steps!!
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Add steps here!!
      # Htmlproofer Action - Updated to use v1 (latest stable version)
      - name: Htmlproofer
        uses: athackst/htmlproofer-action@main # Use the latest stable release
        with:
          directory: ./
        continue-on-error: true
        
      # Cache dependencies
      - name: Cache node modules
        uses: actions/cache@v3
        with:
         path: ~/.npm
         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
         restore-keys: |
          ${{ runner.os }}-node-

      #  Style Lint YAML
      - name: stylelint
        uses: actions-hub/stylelint@master
        with:
          files: '**/*.css'


        
      # End additional steps!!
