# Simple workflow for PRs in GitHub
name: GitHub Actions PR Workflow

on:
  # Runs on pull requests to main branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Add additional jobs here!!

  # End additional job steps!!
  lint:
    runs-on: ubuntu-latest
    outputs:
      status: $({ steps.lint-html.outcome )}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: List Files
        run: find . -name "*.css"
        
      # Add steps here!!
      # Htmlproofer Action - Updated to use v1 (latest stable version)
      - name: Htmlproofer
        uses: athackst/htmlproofer-action@main # Use the latest stable release
        with:
          directory: ./
        continue-on-error: true
    
      # Samuel Mosher: Validate HTML with html5-validator
      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: "./"
        continue-on-error: true # Do not fail the workflow if this step fails
       
      # Devin Bowers : Actions comment pull request
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hello world ! :wave:

      # Jessalyn Heckel: CSS Linter With stylelint
      - name: stylelint
        uses: actions-hub/stylelint@master
        continue-on-error: true
        env:
          PATTERN: "**/*.css"
          
        #env:
          #args: './assets/css/*.css' 
         # PATTERN: "*.css"
       
      # Teguh add peaceiris  
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      # Jonathan Misenheimer: Add spellcheck to workflow
      # This step runs PySpelling to check for spelling errors
      - uses: actions/checkout@v4
      
      - name: Run PySpelling as a GitHub action
        uses: sbates130272/spellcheck-github-actions@v0.6.0
      
      # End additional steps!!